import { useEffect } from 'react';
import { Link, Navigate, useParams } from 'react-router-dom';
import { Reveal } from '../components/ui/Reveal';
import { useScrollReveal } from '../hooks/useScrollReveal';
import { setMeta } from '../lib/meta';

/* ==========================================================================
   LEGAL / POLICY PAGES (§83)
   Same visual system as the rest of the store.

   These describe how each policy works in neutral terms. They deliberately
   contain no invented specifics — no return windows, delivery promises or
   fee amounts — because those are commercial commitments only the business
   can make. A notice at the foot of each page makes that explicit.
   ========================================================================== */

interface Section {
  heading: string;
  body: string[];
}

interface Policy {
  title: string;
  intro: string;
  sections: Section[];
}

const POLICIES: Record<string, Policy> = {
  shipping: {
    title: 'Shipping',
    intro:
      'How orders are packed, dispatched and tracked once you have completed checkout.',
    sections: [
      {
        heading: 'Dispatch',
        body: [
          'Orders are prepared once payment has been confirmed by the payment provider. Until that confirmation arrives, an order is not considered placed.',
          'You will see the current state of your order in your account as it changes.',
        ],
      },
      {
        heading: 'Delivery estimates',
        body: [
          'Delivery timelines depend on the destination address and the courier serving it. The estimate applicable to your order is shown at checkout before you pay.',
          'We do not publish a single blanket delivery promise, because the honest answer varies by location.',
        ],
      },
      {
        heading: 'Tracking',
        body: [
          'When a courier collects your parcel, the tracking reference they issue is attached to your order and shown in your account.',
          'Tracking information is passed through exactly as the courier reports it. We do not generate or estimate tracking data ourselves.',
        ],
      },
      {
        heading: 'Delivery problems',
        body: [
          'If a parcel is delayed, damaged or marked delivered but not received, contact support with your order reference and we will take it up with the courier.',
        ],
      },
    ],
  },
  returns: {
    title: 'Returns & exchanges',
    intro: 'What to do if a piece isn’t right, and how refunds are handled.',
    sections: [
      {
        heading: 'Eligibility',
        body: [
          'Items should be unworn, unwashed and returned with any original tags and packaging intact.',
          'Some categories may be excluded for hygiene reasons. Where that applies, it is stated on the product page.',
        ],
      },
      {
        heading: 'Starting a return',
        body: [
          'Request a return from the relevant order in your account, or contact support with your order reference.',
          'You will be told how to send the item back before you post anything.',
        ],
      },
      {
        heading: 'Refunds',
        body: [
          'Once a returned item has been received and checked, the refund is issued to the original payment method.',
          'The time it then takes to appear depends on your bank or payment provider.',
        ],
      },
      {
        heading: 'Exchanges',
        body: [
          'Where an exchange is possible it depends on the replacement being in stock at the time your return is processed.',
        ],
      },
    ],
  },
  privacy: {
    title: 'Privacy',
    intro: 'What information Apna Store collects, why, and what we do with it.',
    sections: [
      {
        heading: 'What we collect',
        body: [
          'Information you give us directly: your name, contact details and delivery address when you place an order or get in touch.',
          'Information generated by using the site: your bag and saved items, which are kept in your browser so they survive a refresh.',
        ],
      },
      {
        heading: 'How it is used',
        body: [
          'To process and deliver your orders, to respond when you contact support, and to keep the store secure and working correctly.',
          'We do not sell your personal information.',
        ],
      },
      {
        heading: 'Payment information',
        body: [
          'Card and payment details are handled by the payment provider over an encrypted connection. Apna Store does not store your card number.',
        ],
      },
      {
        heading: 'Your choices',
        body: [
          'You can ask what personal data we hold about you, ask for it to be corrected, or ask for it to be deleted, by contacting support.',
        ],
      },
    ],
  },
  terms: {
    title: 'Terms of use',
    intro: 'The basis on which you may use the Apna Store website.',
    sections: [
      {
        heading: 'Using the site',
        body: [
          'You may browse and shop for your own personal use. Please do not attempt to disrupt the site, access other people’s accounts, or scrape it at scale.',
        ],
      },
      {
        heading: 'Products and pricing',
        body: [
          'We aim to describe every piece accurately and to show the price actually charged. Screen colours vary, so fabric shades may appear slightly different in person.',
          'If a pricing or description error is discovered, we may correct it and will contact you before taking any action on an affected order.',
        ],
      },
      {
        heading: 'Orders',
        body: [
          'An order is only formed once payment has been confirmed and we have accepted it. We may decline an order where there is a stock, payment or delivery problem.',
        ],
      },
      {
        heading: 'Accounts',
        body: [
          'You are responsible for keeping your account credentials secure. Tell us promptly if you believe your account has been accessed by someone else.',
        ],
      },
    ],
  },
};

export default function Legal() {
  const { slug = '' } = useParams();
  const policy = POLICIES[slug];

  useScrollReveal([slug]);

  useEffect(() => {
    if (!policy) return;
    setMeta({
      title: `${policy.title} — Apna Store`,
      description: policy.intro,
    });
  }, [policy]);

  if (!policy) return <Navigate to="/404" replace />;

  return (
    <main id="main" className="bg-ink-800 pt-[var(--header-h)]">
      <header className="shell-wide border-b border-line py-12 sm:py-16">
        <p className="anim-fade t-eyebrow mb-4">Policy</p>
        <h1 className="t-h1 text-bone">
          <span className="line-mask inline-block">
            <span style={{ animationDelay: '120ms' }}>{policy.title}</span>
          </span>
        </h1>
        <p className="anim-rise t-lead mt-5 max-w-prose2" style={{ animationDelay: '300ms' }}>
          {policy.intro}
        </p>
      </header>

      <div className="shell-wide section-y">
        <div className="grid gap-12 lg:grid-cols-[14rem_minmax(0,1fr)] lg:gap-20">
          {/* ---- Policy switcher ---- */}
          <nav aria-label="Policies" className="lg:sticky lg:top-[calc(var(--header-h)+1.5rem)] lg:self-start">
            <ul className="no-scrollbar -mx-[var(--shell-pad)] flex gap-2 overflow-x-auto px-[var(--shell-pad)] lg:mx-0 lg:flex-col lg:gap-1 lg:px-0">
              {Object.entries(POLICIES).map(([key, p]) => (
                <li key={key} className="shrink-0">
                  <Link
                    to={`/legal/${key}`}
                    aria-current={key === slug ? 'page' : undefined}
                    className={
                      key === slug
                        ? 'flex min-h-[40px] items-center whitespace-nowrap rounded-full bg-bone px-4 text-sm text-ink-900 lg:rounded-lg lg:bg-ink-700 lg:text-bone'
                        : 'flex min-h-[40px] items-center whitespace-nowrap rounded-full px-4 text-sm text-bone-muted transition-colors hover:text-bone lg:rounded-lg'
                    }
                  >
                    {p.title}
                  </Link>
                </li>
              ))}
            </ul>
          </nav>

          {/* ---- Body ---- */}
          <article className="max-w-prose2">
            {policy.sections.map((section, i) => (
              <Reveal key={section.heading} index={i} as="section" className="mb-10">
                <h2 className="t-h3 mb-4 text-bone">{section.heading}</h2>
                {section.body.map((para) => (
                  <p key={para} className="t-body mb-3">
                    {para}
                  </p>
                ))}
              </Reveal>
            ))}

            {/* Explicit, visible honesty about the limits of this text */}
            <Reveal index={policy.sections.length}>
              <aside className="surface mt-4 rounded-xl p-6">
                <p className="t-eyebrow mb-3">Please note</p>
                <p className="t-body text-sm">
                  This page describes how the policy works in general terms. It
                  intentionally omits specific windows, timeframes and fees,
                  because those are commercial commitments that Apna Store must
                  set and publish itself. Please confirm the exact terms with
                  support before relying on them.
                </p>
                <Link
                  to="/support"
                  className="link-underline mt-4 inline-block text-sm text-bone"
                >
                  Contact support
                </Link>
              </aside>
            </Reveal>
          </article>
        </div>
      </div>
    </main>
  );
}
